version: 2
updates:
 - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/client"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/eureka-server"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/service"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: "/zipkin-server"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
